### ISSUE TITLE
Dynamic tags

### ISSUE THREAD

**Issue by adamgotterer** [Shopify/statsd-instrument#67]
Is it possible to generate dynamic tags in a similar same way that you can generate dynamic measurement names?

**Comment by wvanbergen** [comment]
No, this is currently not supported. This would be a nice addition though, I'll gladly accept patches for this.

**Comment by adamgotterer** [comment]
PR #71

**Comment by gsdean** [comment]
Is there still an appetite to accept this enhancement? If so, I'll submit a new PR addressing the feedback from @wvanbergen

**Comment by wvanbergen** [comment]
Depends on what and how.

We generally haven't had much appetite for dynamic tags, because we don't really use the meta-programming methods anymore. It tends to be more straightforward to manually call `StatsD.increment` compared to having to use a complex API that has to support all kinds of flexibility.

I would still be willing to consider accepting it though. Main requirement is that it means no slowdown for people who are not using this feature. This library is used in many of our hottest code paths so we cannot allow performance regressions. I would also suggest you first come up with an API proposal before doing the full implementation.
