### ISSUE TITLE
Not being able to control backends if initialized outside application

### ISSUE THREAD

**Issue by magnudae** [Shopify/statsd-instrument#73]
Hi.
I am trying to initialiaze a backend from another gem which does almost every app_config for my apps. Here I want to set correct prefixes and backend.

The problem is that StatsD is overwriting my backend with the default logger-backend.  
Is there any way to turn of the fallback backends? 
I would like to be in control of what StatsD backend is set in the different environments myself.

**Comment by wvanbergen** [comment]
The problem is that right now, the StatsD object is a singleton. This is a known issue that we want to fix (see https://github.com/Shopify/statsd-instrument/issues/64). Once a fix for that lands this should be easy to implement.

Until that time, you are dependent on the load order. The backend is initialized as soon as you interact with the library in some way: https://github.com/Shopify/statsd-instrument/blob/master/lib/statsd/instrument.rb#L252-L254. If you set `StatsD.backend` before that happens, the default backend should never get initialized. You can always override `StatsD.backend` after the fact as well.

**Comment by magnudae** [comment]
Thank you for the fast response. Will try to use the fix you suggested
