### ISSUE TITLE
Not working from resque jobs on heroku

### ISSUE THREAD

**Issue by exterm** [Shopify/statsd-instrument#94]
Heroku executes resque workers in `RAILS_ENV=resque`, which makes statsd-instrument fall back to local logging:

https://github.com/Shopify/statsd-instrument/blob/154487eb6a1d8e16039eae5826b90fe7cf5c05b7/lib/statsd/instrument/environment.rb#L14

![screen shot 2016-09-27 at 4 23 45 pm](https://cloud.githubusercontent.com/assets/239580/18891403/0f5eed96-84d3-11e6-8019-94b80736aa63.png)

the list in `environment.rb:14` should probably contain `resque` too.

**Comment by wvanbergen** [comment]
`resque` is not really a standard environment name, so I rather not hard-code that into this general purpose gem. 

In your application's `config/environments/resque.rb`, you can set `StatsD.backend` yourself, instead of letting the environment detection do that. Or you can run resque in the more standard `production` environment by editing your application's `Procfile`.
